### ISSUE TITLE
Wrong rdkit version requirement

### ISSUE THREAD

**Issue by mgbaltussen** [Will-Robin/NorthNet#5]
For some reason NorthNet gives an error whenever I try to perform a clean install. I do have rdkit installed, and have tried multiple versions, but all give the same error. 

> ERROR: Could not find a version that satisfies the requirement rdkit>=2021.09.4 (from northnet) (from versions: none)
ERROR: No matching distribution found for rdkit>=2021.09.4

Any thoughts/solutions?

**Comment by mgbaltussen** [comment]
Also, I think the yaml version is incorrect. Only `yaml >= 0.2` and `pyyaml>=5.4` exist :).

**Comment by Will-Robin** [comment]
How are you performing the installation? I usually create an environment containing the rdkit first, then install the other dependencies.

**Comment by Will-Robin** [comment]
yaml should be pyyaml, I've changed that in main

**Comment by Will-Robin** [comment]
I'm using conda to manage packages, that might be making the difference. Conda is recommended for the installation, it seems be be available on pip [here](https://pypi.org/project/rdkit-pypi/). Needs a bit of looking into.

**Comment by Will-Robin** [comment]
I've added the dependencies in `environment.yml` and used it for a successful installation. `setup.py` is still there so `pip install -e .` works. I couldn't find a more straightforward way to achieve similar results using `conda`.
